### ISSUE TITLE
Question: Scroll Speed?

### ISSUE THREAD

**Issue by Alexyoe** [freddydumont/gatsby-plugin-smoothscroll#17]
Is there any way to adjust the speed of the scrolling? I'd like to reduce the speed if possible.

**Comment by freddydumont** [comment]
This plugin's main export is bare-bones. The actual purpose of the plugin is to inject the polyfill in gatsby's lifecycle hook. 

Feel free to check out the code to implement a custom solution for the actual scrolling.
