### ISSUE TITLE
how to import?

### ISSUE THREAD

**Issue by andrisLaduzans** [freddydumont/gatsby-plugin-smoothscroll#2]
`import scrollTo from "gatsby-plugin-smoothscroll"` gives 
Module '"/..../node_modules/gatsby-plugin-smoothscroll/index"' has no default export.ts(1192)
but it does compile tho, i just want to get rid of the error log.

changing to `import * as scrollTo from "gatsby-plugin-smoothscroll"` breaks programm so it cannot even compile. 

i am using typescript, is there any suggested method?

**Comment by freddydumont** [comment]
I'll have a look when I have some time. Maybe we can rewrite the package in TypeScript. I was planning on doing it anyway.

**Comment by freddydumont** [comment]
@andrisLaduzans I added types in the latest version, let me know if it fixes your issue.

```bash
# npm
npm install gatsby-plugin-smoothscroll@latest

# yarn
yarn add gatsby-plugin-smoothscroll@latest
```

**Comment by andrisLaduzans** [comment]
oh, thanks, dude. I actually missed last post. Happy holidays!
