### ISSUE TITLE
Could there be a conditional check? If selector is not null?

### ISSUE THREAD

**Issue by TimmyR** [freddydumont/gatsby-plugin-smoothscroll#4]
Hi,

Could there be a check if the selector is not null? I get this error:
`TypeError: Cannot read property 'scrollIntoView' of null`
on `node_modules/gatsby-plugin-smoothscroll/index.js:11`

**Comment by freddydumont** [comment]
Fixed in 1.1.0

**Comment by TimmyR** [comment]
Great! Thumbs up!
