### ISSUE TITLE
Suggestion: Add option for offset to account for fixed nav/header

### ISSUE THREAD

**Issue by hades200082** [freddydumont/gatsby-plugin-smoothscroll#5]
To avoid a fixed nav/header overlapping the content when scrolling down having the option to set an offset height either in config, or as an argument to the smoothScroll function would be useful.

**Comment by freddydumont** [comment]
I don't have time to look into this right now but feel free to submit a PR.

Otherwise the `smoothScroll` function isn't necessary for the polyfill to work so you can roll out your own.

**Comment by freddydumont** [comment]
Ideas for an implementation of `scrollWithOffset`:

- get the `y` coordinate of the element with `getBoundingClientRect().top`
- accept an offset in a config object

```javascript
const top = element.getBoundingClientRect().top - offset;

window.scrollTo({
  top,
  behavior: 'smooth'
});
 ```

**Comment by PatrickFranz** [comment]
Any chance the PR going to be merged?

**Comment by freddydumont** [comment]
I might get around to testing it properly at some point. 

Keep in mind that the main purpose of this library is the polyfill. The plugin does its job the moment it's included in your config.

There is nothing Gatsby-specific about the helper function, so adding weight for all users to support an edge case is a tradeoff to consider as well.

You shouldn't depend on it if it's not working out of the box. It's provided as a rudimentary convenience for the most basic of cases.

**Comment by PatrickFranz** [comment]
So no then. :smiley:

**Comment by freddydumont** [comment]
Closing this for the reason described here: https://github.com/freddydumont/gatsby-plugin-smoothscroll/issues/5#issuecomment-832058674
