### ISSUE TITLE
window.scrollTo doesn't smooth scroll

### ISSUE THREAD

**Issue by thomasmorice** [freddydumont/gatsby-plugin-smoothscroll#6]
As far as I understand from the documentation, the only thing I need to do in my gatsby app is adding 
`gatsby-plugin-smoothscroll` to my gatsby-config file.

Unfortunately, using `window.scrollTo` is still not smooth in safari. 
I can't use the scrollTo helper since I need to calculate in pixels where I want to scroll, then execute the native function.

**Comment by freddydumont** [comment]
You're correct, all that is needed for the polyfill to work is to add the plugin to your gatsby config. 

Are you passing a configuration object with `{ behavior: smooth }` to your `scrollTo` function?

Eg. `window.scroll({ top: 2500, left: 0, behavior: 'smooth' });`

**Comment by thomasmorice** [comment]
I was using scrollTo and the smooth behavior as a css property : 
`html {
  scroll-behavior: smooth;
}`
using scroll the way you did, with `behavior: 'smooth'` seem to work as expected, thank you 👍
